/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refaccionaria.Altas;

import java.awt.Component;
import java.sql.Connection;
import javax.swing.*;
import refaccionaria.Acciones.Conexion;
import refaccionaria.Acciones.Insert;
import refaccionaria.Validaciones.ValidarC;

/**
 *
 * @author jesanher
 */
public class Alta_Empleado extends javax.swing.JPanel {

    Insert in = new Insert();
    Connection conex;
    ValidarC v = new ValidarC();
    Conexion c = new Conexion();
    private Component rootPane;

    public Alta_Empleado() {
        initComponents();
        c.ConectarBD();
    }

    public void Limpiar() {
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        comboBStatus.setSelectedIndex(-1);
        txtTelefono.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new refaccionaria.swing.txtf.TextFielda();
        txtApellidoP = new refaccionaria.swing.txtf.TextFielda();
        txtApellidoM = new refaccionaria.swing.txtf.TextFielda();
        txtTelefono = new refaccionaria.swing.txtf.TextFielda();
        txtCorreo = new refaccionaria.swing.txtf.TextFielda();
        jLabel1 = new javax.swing.JLabel();
        bGuardar = new javax.swing.JButton();
        comboBStatus = new refaccionaria.swing.txtf.ComboBoxA();
        Bcancelar = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 680));

        txtNombre.setLabelText("Nombre  del Empleado");

        txtApellidoP.setLabelText("Apelldio Paterno");

        txtApellidoM.setLabelText("Apellido materno");

        txtTelefono.setLabelText("Numero Telefonico");

        txtCorreo.setLabelText("Correo electronico");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleado.png"))); // NOI18N
        jLabel1.setText("Guardar Empleado");

        bGuardar.setBackground(new java.awt.Color(44, 203, 87));
        bGuardar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bGuardar.setForeground(new java.awt.Color(25, 25, 25));
        bGuardar.setText("Guardar");
        bGuardar.setBorder(null);
        bGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        comboBStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado normal", "Encargado" }));
        comboBStatus.setSelectedIndex(-1);
        comboBStatus.setLabeText("Status del empleado");

        Bcancelar.setBackground(new java.awt.Color(235, 47, 47));
        Bcancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Bcancelar.setForeground(new java.awt.Color(25, 25, 25));
        Bcancelar.setText("Cancelar");
        Bcancelar.setBorder(null);
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(comboBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_BcancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre_Emp = txtNombre.getText();
            String ap_Pat = txtApellidoP.getText();
            String ap_Mat = txtApellidoM.getText();
            String status = comboBStatus.getSelectedItem().toString();
            String tel_Empleado = txtTelefono.getText();
            String correo = txtCorreo.getText();
            int status_Empleado;

            if (!nombre_Emp.equals("") && !ap_Pat.equals("") && !ap_Mat.equals("") && !tel_Empleado.equals("") && !correo.equals("")) {
                if (status.equals("Empleado normal")) {
                    status_Empleado = 1;
                    if (v.ValidarEmpleado(nombre_Emp, ap_Pat, ap_Mat) == 0) {
                        JOptionPane.showMessageDialog(rootPane, "El Empleado ya fue registrado!!");
                    } else {
                        if (in.insertEmpleado(nombre_Emp, ap_Pat, ap_Mat, status_Empleado, tel_Empleado, correo)) {
                            JOptionPane.showMessageDialog(rootPane, "Registro exitoso!!");
                        } else {
                            JOptionPane.showConfirmDialog(rootPane, "Registro fallido");
                        }
                    }
                }
                if (status.equals("Encargado")) {
                    status_Empleado = 2;
                    if (v.ValidarEmpleado(nombre_Emp, ap_Pat, ap_Mat) == 0) {
                        JOptionPane.showMessageDialog(rootPane, "El Empleado ya fue registrado!!");
                    } else {
                        if (in.insertEmpleado(nombre_Emp, ap_Pat, ap_Mat, status_Empleado, tel_Empleado, correo)) {
                            JOptionPane.showMessageDialog(rootPane, "Registro exitoso!!");
                        } else {
                            JOptionPane.showConfirmDialog(rootPane, "Registro fallido");
                        }
                    }
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Favor de ingresar todos datos!!!!");
            }

        } catch (Exception e) {
            System.out.println("error:" + e.getMessage());
        }
        Limpiar();
    }//GEN-LAST:event_bGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancelar;
    private javax.swing.JButton bGuardar;
    private refaccionaria.swing.txtf.ComboBoxA comboBStatus;
    private javax.swing.JLabel jLabel1;
    private refaccionaria.swing.txtf.TextFielda txtApellidoM;
    private refaccionaria.swing.txtf.TextFielda txtApellidoP;
    private refaccionaria.swing.txtf.TextFielda txtCorreo;
    private refaccionaria.swing.txtf.TextFielda txtNombre;
    private refaccionaria.swing.txtf.TextFielda txtTelefono;
    // End of variables declaration//GEN-END:variables
}
