package refaccionaria.Altas;

import java.awt.Component;
import java.sql.*;
import javax.swing.*;
import refaccionaria.Acciones.Conexion;
import refaccionaria.Acciones.Insert;
import refaccionaria.Validaciones.ValidarC;

public class Alta_Clientes extends javax.swing.JPanel {

    Insert in = new Insert();
    Connection conex;
    ValidarC v = new ValidarC();
    Conexion c = new Conexion();
    private Component rootPane;

    /**
     * Creates new form Alta_Clientes
     */
    public Alta_Clientes() {
        initComponents();
        conex = c.ConectarBD();
        //in = new Insert();
        //  v = new ValidarC();
    }

    public void Limpiar() {
        txtNombre.setText("");
        txtApelleidoP.setText("");
        txtApellidoM.setText("");
        txtaNumT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new refaccionaria.swing.txtf.TextFielda();
        txtApelleidoP = new refaccionaria.swing.txtf.TextFielda();
        txtApellidoM = new refaccionaria.swing.txtf.TextFielda();
        txtaNumT = new refaccionaria.swing.txtf.TextFielda();
        jLabel1 = new javax.swing.JLabel();
        bGuardar = new javax.swing.JButton();
        Bcancelar = new javax.swing.JButton();

        setOpaque(false);

        txtNombre.setLabelText("Nombre del cliente");

        txtApelleidoP.setLabelText("Apellido Paterno");

        txtApellidoM.setLabelText("Apellido materno");

        txtaNumT.setLabelText("Numero Telefonico");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jLabel1.setText("Clientes");

        bGuardar.setBackground(new java.awt.Color(44, 203, 87));
        bGuardar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bGuardar.setForeground(new java.awt.Color(25, 25, 25));
        bGuardar.setText("Guardar");
        bGuardar.setBorder(null);
        bGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        Bcancelar.setBackground(new java.awt.Color(235, 47, 47));
        Bcancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Bcancelar.setForeground(new java.awt.Color(25, 25, 25));
        Bcancelar.setText("Cancelar");
        Bcancelar.setBorder(null);
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtaNumT, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApelleidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtApelleidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtaNumT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_BcancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = txtNombre.getText();
            String ap_Pat = txtApelleidoP.getText();
            String ap_Mat = txtApellidoM.getText();
            String telefono = txtaNumT.getText();
            
            if (!nombre.equals("") && !ap_Pat.equals("") && !ap_Mat.equals("") && !telefono.equals("")) {
                if (v.ValidarCliente(nombre, ap_Pat, ap_Mat) == 0) {
                    JOptionPane.showMessageDialog(rootPane, "El cliente ya fue registrado!!");
                } else {
                    if (in.insertCliente(nombre, ap_Pat, ap_Mat, telefono)) {
                        JOptionPane.showMessageDialog(rootPane, "Registro exitoso!!");
                    } else {
                        JOptionPane.showConfirmDialog(rootPane, "Registro fallido");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Favor de ingresar todos datos!!!!");
            }

            //      v.ValidarCliente(nombre, ap_Pat, ap_Mat);
            //in.insertCliente(nombre, ap_Pat, ap_Mat, telefono);
        } catch (Exception e) {
            System.out.println("error:" + e.getMessage());
        }
        Limpiar();
    }//GEN-LAST:event_bGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JLabel jLabel1;
    private refaccionaria.swing.txtf.TextFielda txtApelleidoP;
    private refaccionaria.swing.txtf.TextFielda txtApellidoM;
    private refaccionaria.swing.txtf.TextFielda txtNombre;
    private refaccionaria.swing.txtf.TextFielda txtaNumT;
    // End of variables declaration//GEN-END:variables
}
